name: CI

on:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "*"
  pull_request:

jobs:
  before:
    name: Check for dependency installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install wheel && pip install --prefer-binary -r requirements.txt

  build_and_publish:
    needs: before
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install wheel && pip install --prefer-binary -r requirements.txt -r test_requirements.txt
      - name: Build source distribution
        run: python setup.py sdist
      - name: Publish latest on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
