name: CI

on:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "*"
  pull_request:

jobs:
  before:
    name: Check for dependency installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install wheel && pip install --prefer-binary -r requirements.txt

  tests:
    needs: before
    name: ${{ matrix.os }}${{ matrix.arch }} - Python ${{ matrix.python-version }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
        python-version: ["3.6.x", "3.7.x", "3.8.x", "3.9.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: pip install wheel && pip install --prefer-binary -r requirements.txt -r test_requirements.txt
      - name: Build
        run: |
          python setup.py install
      - name: Run tests
        run: |
          pytest
      - name: Run coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_API_TOKEN }}
          verbose: true
  build_and_publish:
    needs: tests
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install wheel && pip install --prefer-binary -r requirements.txt -r test_requirements.txt
      - name: Build source distribution
        run: python setup.py sdist
      - name: Publish latest on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
